# Generated by Django 4.1.4 on 2022-12-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_pagos_monto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagos',
            table='pagos',
        ),
    ]
