# Generated by Django 4.1.4 on 2022-12-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expired_payments',
            table='expired_payments',
        ),
        migrations.AlterModelTable(
            name='payment_user',
            table='payment_user',
        ),
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
